CREATE PROCEDURE change_time (
	@time DATETIME,
    @batch INT
)
AS
BEGIN
	SELECT *
	FROM STREAMLINE.DBO.CHANGE_LOG
	WHERE CHANGE_DATE > @time
	ORDER BY CHANGE_DATE ASC
	OFFSET 0 ROWS
	FETCH NEXT @batch ROWS ONLY
END