CREATE PROCEDURE change_time_id (
	@time DATETIME,
    @id BIGINT,
    @batch INT
)
AS
BEGIN
	SELECT *
	FROM STREAMLINE.DBO.CHANGE_LOG
	WHERE
		(CHANGE_DATE > @time)
		OR
		(CHANGE_DATE = @time AND ID > @id)
	ORDER BY CHANGE_DATE, ID ASC
	OFFSET 0 ROWS
	FETCH NEXT @batch ROWS ONLY
END
